services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: ${ID}:${ID}
    networks:
      - nginx_proxy
    volumes:
      - ${DIRECTORY}/database.db:/database.db
      - ${DIRECTORY}/img:/img
      - ${HOMEDIR}:/srv
    command: --disable-exec
    restart: unless-stopped

networks:
  nginx_proxy:
    external: true
