services:
  pairdrop:
    image: lscr.io/linuxserver/pairdrop:latest
    container_name: pairdrop
    hostname: pairdrop
    env_file: pairdrop.env
    labels:
      - io.containers.autoupdate=registry
      - PODMAN_SYSTEMD_UNIT=container-pairdrop.service
      - flame.type=application
      - flame.name=pairdrop
      - flame.url=https://drop.jeremky.fr
      - flame.icon=access-point
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true
