services:
  pairdrop:
    image: lscr.io/linuxserver/pairdrop:latest
    container_name: pairdrop
    hostname: pairdrop
    env_file: pairdrop.env
    labels:
      - flame.type=application
      - flame.name=PairDrop
      - flame.url=https://drop.jeremky.fr
      - flame.icon=access-point
    networks:
      - nginx_proxy
    restart: always

networks:
  nginx_proxy:
    external: true
