services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    hostname: emulatorjs
    env_file: emulatorjs.env
    labels:
      - flame.type=application
      - flame.name=EmulatorJS
      - flame.url=https://emu.jeremky.fr
      - flame.icon=nintendo-game-boy
    cpus: 2
    networks:
      - nginx_proxy
    volumes:
      - /opt/containers/emulatorjs/config:/config
      - /opt/containers/emulatorjs/data:/data
    restart: always

networks:
  nginx_proxy:
    external: true
