services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    hostname: transmission
    labels:
      - io.containers.autoupdate=registry
      - PODMAN_SYSTEMD_UNIT=container-transmission.service
      - flame.type=application
      - flame.name=Transmission
      - flame.url=https://transmission.jeremky.fr
      - flame.icon=download-box
    env_file: transmission.env
    networks:
      - nginx_proxy
    volumes:
      - /opt/transmission/data:/config
      - /opt/transmission/downloads:/downloads
      - /opt/transmission/folder:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp

networks:
  nginx_proxy:
    external: true
