services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    networks:
      - nginx_proxy
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - data:/config
    restart: unless-stopped

networks:
  nginx_proxy:
    external: true

volumes:
  data:
