services:
  nextcloud-db:
    image: postgres:latest
    container_name: nextcloud-db
    networks:
      - default
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - ${DIRECTORY}/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    networks:
      - default
      - nginx_proxy
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${DIRECTORY}/config:/config
      - ${DIRECTORY}/data:/data
    depends_on:
      - nextcloud-db
    restart: unless-stopped

networks:
  default:
    external: false
  nginx_proxy:
    external: true
