services:
  nginx:
    image: lscr.io/linuxserver/swag:latest
    container_name: nginx
    labels:
      - "io.containers.autoupdate=registry"
      - "PODMAN_SYSTEMD_UNIT=container-nginx.service"
    cap_add:
      - NET_ADMIN
    networks:
      - proxy
    env_file: ./.env
    volumes:
      - ${DIRECTORY}:/config
    ports:
      - ${HTTPPORT}:80
      - ${HTTPSPORT}:443
    restart: always

networks:
  proxy:
    external: false
