services:
  nginx:
    image: lscr.io/linuxserver/swag:latest
    container_name: nginx
    hostname: nginx
    env_file: nginx.env
    cap_add:
      - NET_ADMIN
    networks:
      - proxy
    volumes:
      - /opt/containers/nginx:/config
    ports:
      - 80:80
      - 443:443
    restart: always

networks:
  proxy:
    external: false
