services:
  nginx:
    image: lscr.io/linuxserver/swag:latest
    container_name: nginx
    hostname: nginx
    labels:
      - io.containers.autoupdate=registry
      - PODMAN_SYSTEMD_UNIT=container-nginx.service
    cap_add:
      - NET_ADMIN
    networks:
      - proxy
    env_file: nginx.env
    volumes:
      - /opt/nginx:/config
    ports:
      - 80:80
      - 443:443

networks:
  proxy:
    external: false
