services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    hostname: heimdall
    labels:
      - io.containers.autoupdate=registry
      - PODMAN_SYSTEMD_UNIT=container-heimdall.service
    networks:
      - nginx_proxy
    env_file: heimdall.env
    volumes:
      - /opt/heimdall/config:/config

networks:
  nginx_proxy:
    external: true
