services:
  mcserver:
    image: docker.io/itzg/minecraft-server:latest
    container_name: mcserver
    hostname: mcserver
    env_file: mcserver.env
    labels:
      - io.containers.autoupdate=registry
      - PODMAN_SYSTEMD_UNIT=container-mcserver.service
    cpus: 2
    mem_limit: 2G
    volumes:
      - /opt/mcserver:/data
    ports:
      - 25565:25565
    tty: true
    stdin_open: true
