services:
  mcserver:
    image: docker.io/itzg/minecraft-server:latest
    container_name: mcserver
    hostname: mcserver
    cpus: 2
    mem_limit: 2G
    env_file: mcserver.env
    volumes:
      - /opt/mcserver:/data
    ports:
      - 25565:25565
    tty: true
    stdin_open: true
