services:
  freshrss-db:
    image: postgres:latest
    container_name: freshrss-db
    networks:
      - network
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - ${DIRECTORY}/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    networks:
      - network
      - nginx_proxy
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${DIRECTORY}/config:/config
    restart: unless-stopped

networks:
  network:
    external: false
  nginx_proxy:
    external: true
