services:
  filebrowser:
    image: docker.io/filebrowser/filebrowser
    container_name: filebrowser
    hostname: filebrowser
    labels:
      - flame.type=application
      - flame.name=File Browser
      - flame.url=https://files.jeremky.fr
      - flame.icon=file-download
    networks:
      - nginx_proxy
    volumes:
      - ./files/database.db:/database/filebrowser.db
      - ./files/settings.json:/.filebrowser.json
      - /home:/srv
    restart: always

networks:
  nginx_proxy:
    external: true
