services:
  filebrowser:
    image: docker.io/filebrowser/filebrowser
    container_name: filebrowser
    labels:
      - "io.containers.autoupdate=registry"
      - "PODMAN_SYSTEMD_UNIT=container-filebrowser.service"
    networks:
      - nginx_proxy
    volumes:
      - ./files/database.db:/database.db
      - ${HOMEDIR}:/srv
    command: --disable-exec
    restart: always

networks:
  nginx_proxy:
    external: true
