services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: ${UID}:${GID}
    networks:
      - nginx_proxy
    volumes:
      - ${DBDIR}/database.db:/database.db
      - ${IMGDIR}/img:/img
      - ${HOMEDIR}:/srv
    command: --disable-exec
    restart: unless-stopped

networks:
  nginx_proxy:
    external: true
