services:
  xonotic:
    image: docker.io/itom34/xonotic:latest
    container_name: xonotic
    labels:
      - "io.containers.autoupdate=registry"
      - "PODMAN_SYSTEMD_UNIT=container-xonotic.service"
    volumes:
      - ${DIRECTORY}:/root/.xonotic/
    ports:
      - 0.0.0.0:26000:26000/tcp
      - 0.0.0.0:26000:26000/udp
    restart: always
