services:
  xonotic:
    image: docker.io/itom34/xonotic:latest
    container_name: xonotic
    hostname: xonotic
    cpus: 2
    mem_limit: 1G
    volumes:
      - ./files:/root/.xonotic/
    ports:
      - 26000:26000/tcp
      - 26000:26000/udp
    restart: always
