services:
  xonotic:
    image: docker.io/itom34/xonotic:latest
    container_name: xonotic
    hostname: xonotic
    cpus: 2
    mem_limit: 1G
    volumes:
      - ./files:/root/.xonotic/
    ports:
      - 26000:26000/tcp
      - 26000:26000/udp
    healthcheck:
      test: ["CMD", "pgrep", "xonotic"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
