services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: rslsync
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${DIRECTORY}/config:/config
      - ${DIRECTORY}/downloads:/downloads
      - ${WORKDIR}:/sync
    ports:
      - ${PORT}:8888
      - 55555:55555
    restart: unless-stopped
