services:
  uptimekuma:
    image: docker.io/louislam/uptime-kuma:latest
    container_name: uptimekuma
    hostname: uptimekuma
    labels:
      - io.containers.autoupdate=registry
      - PODMAN_SYSTEMD_UNIT=container-uptimekuma.service
      - flame.type=application
      - flame.name=Uptime Kuma
      - flame.url=https://kuma.jeremky.fr
      - flame.icon=chart-line
    networks:
      - nginx_proxy
    volumes:
      - /opt/uptimekuma:/app/data
      - /var/run/podman/podman.sock:/var/run/docker.sock

networks:
  nginx_proxy:
    external: true
