services:
  diun:
    image: docker.io/crazymax/diun:latest
    container_name: diun
    hostname: diun
    env_file: diun.env
    labels:
      - io.containers.autoupdate=registry
      - PODMAN_SYSTEMD_UNIT=container-diun.service
    volumes:
      - data:/data
      - /run/podman/podman.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "pgrep", "diun"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  data:
