services:
  diun:
    image: docker.io/crazymax/diun:latest
    container_name: diun
    hostname: diun
    env_file: diun.env
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "pgrep", "diun"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always

volumes:
  data:
