services:
  authelia:
    image: docker.io/authelia/authelia:latest
    container_name: authelia
    hostname: authelia
    user: 1000:1000
    labels:
      - io.containers.autoupdate=registry
      - PODMAN_SYSTEMD_UNIT=container-authelia.service
      - flame.type=application
      - flame.name=Authelia
      - flame.url=https://auth.jeremky.fr
      - flame.icon=key
    env_file: authelia.env
    networks:
      - nginx_proxy
    volumes:
      - ./files:/config

networks:
  nginx_proxy:
    external: true
