services:
  authelia:
    image: docker.io/authelia/authelia:latest
    container_name: authelia
    hostname: authelia
    env_file: authelia.env
    user: 1000:1000
    networks:
      - nginx_proxy
    volumes:
      - ./files:/config
    restart: always

networks:
  nginx_proxy:
    external: true
