services:
  authelia:
    image: docker.io/authelia/authelia:latest
    container_name: authelia
    hostname: authelia
    env_file: authelia.env
    user: 1000:1000
    labels:
      - io.containers.autoupdate=registry
      - PODMAN_SYSTEMD_UNIT=container-authelia.service
    networks:
      - nginx_proxy
    volumes:
      - ./files:/config

networks:
  nginx_proxy:
    external: true
