services:
  authelia:
    image: docker.io/authelia/authelia:latest
    container_name: authelia
    hostname: authelia
    env_file: authelia.env
    networks:
      - nginx_proxy
    volumes:
      - ./files:/config
    command:
      - "authelia"
      - "--config=/config/configuration.yml"
    restart: always

networks:
  nginx_proxy:
    external: true
