services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ./files:/config
    restart: unless-stopped
