services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    hostname: webtop
    env_file: webtop.env
    labels:
      - io.containers.autoupdate=registry
      - PODMAN_SYSTEMD_UNIT=container-webtop.service
      - flame.type=application
      - flame.name=Webtop
      - flame.url=https://linux.jeremky.fr
      - flame.icon=penguin
    cpus: 2
    mem_limit: 2G
    networks:
      - nginx_proxy
    volumes:
      - /opt/webtop:/config
      - /home/jeremky:/config/jeremky
    shm_size: "1gb"

networks:
  nginx_proxy:
    external: true
