services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    networks:
      - nginx_proxy
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${DIRECTORY}/config:/config
      - ${DIRECTORY}/downloads:/downloads
      - ${WORKDIR}:/sync
    ports:
      - 55555:55555
    restart: unless-stopped

networks:
  nginx_proxy:
    external: true
