services:
  vscode:
    build: .
    context: .
    image: localhost/vscode-hugo:latest
    container_name: vscode
    hostname: vscode
    env_file: vscode.env
    labels:
      - io.containers.autoupdate=local
      - PODMAN_SYSTEMD_UNIT=container-vscode.service
      - flame.type=application
      - flame.name=VS Code
      - flame.url=https://code.jeremky.fr
      - flame.icon=file-code
    cpus: 2
    mem_limit: 2G
    networks:
      - nginx_proxy
    volumes:
      - /opt/vscode:/config
      - /home/jeremky:/home/jeremky

networks:
  nginx_proxy:
    external: true
