services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    env_file: syncthing.env
    labels:
      - io.containers.autoupdate=registry
      - PODMAN_SYSTEMD_UNIT=container-syncthing.service
      - flame.type=application
      - flame.name=Syncthing
      - flame.url=https://sync.jeremky.fr
      - flame.icon=cloud-sync
    networks:
      - nginx_proxy
    volumes:
      - /opt/syncthing:/config
      - /home/jeremky:/data
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp

networks:
  nginx_proxy:
    external: true
